# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0
# Modifications Copyright 2026 Canonical Ltd.

# These annotations may be needed only for Tanzu and Artifact Hub,
# none of which are currently supported by this repository, so let's comment them out for now.
# annotations:
#   licenses: Apache-2.0
apiVersion: v2
# Please make sure that version and appVersion are always the same.
name: common
appVersion: 0.0.1
version: 0.0.1
description: A Library Helm Chart for grouping common logic between charts. This chart is not deployable by itself.
home: https://ubuntu.com/containers/docs
keywords:
  - common
  - helper
  - library
maintainers:
  - name: Canonical Ltd. All Rights Reserved.
    url: https://github.com/canonical/helm-charts
sources:
  - https://github.com/canonical/helm-charts/tree/main/charts/common
type: library
