{{- $secretName := printf "%s-erlang-cookie" (include "rabbitmq.fullname" .) -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
{{ if .Values.clustering.erlangCookie }}
  erlang-cookie: {{ .Values.clustering.erlangCookie | b64enc | quote }}
{{ else if $existing }}
  erlang-cookie: {{ index $existing.data "erlang-cookie" | quote }}
{{ else }}
  erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
{{ end }}
