apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-erlang-cookie
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.clustering.erlangCookie }}
  erlang-cookie: {{ .Values.clustering.erlangCookie | b64enc | quote }}
  {{- else }}
  erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
