summary: Spread tests for the rabbitmq Helm chart

environment:
  HELM_RELEASE: test-rabbitmq
  HELM_REGISTRY: '$(HOST: echo "${HELM_REGISTRY:-}")'
  HELM_REGISTRY_USERNAME: '$(HOST: echo "${HELM_REGISTRY_USERNAME:-}")'
  HELM_REGISTRY_PASSWORD: '$(HOST: echo "${HELM_REGISTRY_PASSWORD:-}")'

execute: |
  # Common file from $PROJECT_ROOT/spread/lib/
  helm-test

restore: |
  helm uninstall "$HELM_RELEASE" --wait || true
